# Generated by Django 5.2.6 on 2025-09-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_candidate',
            field=models.BooleanField(default=True),
        ),
    ]
