# Generated by Django 5.2.6 on 2025-09-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_resume', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='ai_score',
        ),
        migrations.AddField(
            model_name='resume',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
