# Generated by Django 5.2.6 on 2025-11-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
