# Generated by Django 5.2.6 on 2025-11-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_app', '0005_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='consultation_type',
        ),
    ]
