# Generated by Django 5.2.6 on 2025-11-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consult_app', '0007_remove_booking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
