# Generated by Django 5.2.6 on 2025-11-19 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consult_app', '0006_remove_booking_consultation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
    ]
