# Generated by Django 5.2.6 on 2025-11-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_consultant',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
